acronymsInternet = {
'4rever' : 'forever',
'9dade':'novidade',
'abc':'abraco',
'add': 'adicionar',
'ae' : 'e ai',
'aew' : 'e ai',
'aff': 'suspiro',
'afk':'longe do teclado',
'ag':'agora',
'agg' : 'agora',
'aham' : 'sim',
'ahua' : 'risada',
'aka':'tambem conhecido como',
'akbo' : 'acabou',
'akele' : 'aquele',
'aki' : 'aqui',
'amg':'amigo',
'amgo' : 'amigo',
'aosksaoks':'risada',
'asap':'o mais rapido possivel',
'at+' : 'ate mais tarde',
'axo':'acho',
'baum' : 'bom',
'bb' : 'bebe',
'bbeu' : 'bebeu',
'bbl':'volto mais tarde',
'bbq': 'babaca',
'bbs':'volto em um segundo',
'bcnu':'ate a proxima',
'bff':'melhore amigos para sempre',
'bgd' : 'obrigado',
'bj':'beijo',
'bjc':'beijo',
'bjok':'beijo',
'bjos':'beijos',
'bjs': 'beijos',
'bju':'beijo',
'blz' :'beleza',
'blz':'beleza',
'bora' : 'embora',
'boss':'inimigo dificil',
'brb':'volto logo',
'brigs' : 'obrigado',
'brinks': 'sarcasmo',
'btf' : 'boto fe',
'btfe':'boto fe',
'btw':'por falar nisso',
'c':'com',
'cda' : 'cada',
'ce' : 'voce',
'cel' : 'celular',
'cmg' : 'comigo',
'cnte' : 'conte',
'cntg' : 'contigo',
'coments' : 'comentario',
'comg' : 'comigo',
'cs' : 'voces',
'csg':'consiga',
'ct' : 'certeza',
'ctz':'certeza',
'cume' : 'como e',
'cv' : 'conversa',
'cvs' : 'conversar',
'd nda' : 'de nada',
'd':'de',
'd+':'demais',
'demoro' : 'demorou',
'diy':'faca voce mesmo',
'dm':'mensagem direta',
'dmais' : 'demais',
'dp' : 'depois',
'dpois' : 'depois',
'dps' : 'depois',
'eh':'e',
'enqt' : 'enquanto',
'eol' : 'eu',
'fcd' : 'fica com deus',
'fdp' : 'filho da puta',
'fds' : 'fim de semana',
'fikdik':'fica a dica',
'find' : 'vide fds',
'fla':'fala',
'flw':'falou',
'fmz':'firmeza',
'ft': 'foto',
'ftw':'para vitoria',
'fyi':'para sua informação',
'fzr' : 'fazer',
'g2g':'tenho que ir',
'glr':'galera',
'gnt' : 'gente',
'gtg':'tenho que ir',
'hahaha' : 'gargalhada',
'hehehe' : 'risada',
'hj' : 'hoje',
'hr' : 'hora',
'idd' : 'idade',
'idk':'eu nao sei',
'imo':'na minha opiniao',
'jah': 'ja',
'jg':'jogo',
'k':'ok',
'kbca' : 'cabeca',
'kbelo' : 'cabelo',
'kd' : 'cade',
'kda' : 'cada',
'ke' : 'que',
'kkk':'risada',
'ksa':'casa',
'lmfao':'estourando de rir',
'lol': 'rindo alto',
'miga' : 'amiga',
'migz' : 'amigas',
'mlk':'moleque',
'mlke' : 'muleque',
'mooh' : 'amor',
'msg':'mensagem',
'msn':'mesmo',
'mtos':'muitos',
'n':'nao',
'naum':'nao',
'nda' : 'nada',
'net' : 'internet',
'ngm' : 'ninguem',
'nsfw':'inadequado para o ambiente de trabalho',
'obg':'obrigado',
'obgda' : 'obrigada',
'obv' : 'obvio',
'oc' : 'voce',
'okay' : 'tudo certo',
'omg':'ai meu deus',
'p':'para',
'pc' : 'computador',
'pdc' : 'pode crer',
'pde' : 'pode',
'perfoh' : 'perfeito',
'pf':'por favor',
'pfv':'por favor',
'pfvr':'por favor',
'plmdds':'pelo amor de deus',
'plz':'por favor',
'pq':'porque',
'pqe' : 'por que',
'pqp' : 'puta que pariu',
'q':'que',
'qdo' : 'quando',
'qe' : 'que',
'qlqr' : 'qualquer',
'qm' : 'quem',
'qq' : 'qualquer',
'qrendo' : 'querendo',
'qria' : 'queria',
'qro' : 'quero',
'qse' : 'quase',
'qto' : 'quanto',
'qzr' : 'quiser',
'rly':'serio',
'rofl':'rolando de rir',
'rs' : 'risos',
'rsrsrsrs':'risada',
'rsvp':'responda por favor',
's':'sim',
'sdds':'saudades',
'sddz' : 'saudades',
'sdv':'segue de volta',
'shuashuahs':'risada',
'smp' : 'sempre',
'soh' : 'so',
'sqn':'so que nao',
'sux' : 'algo ruim',
't+' : 'ate mais',
'ta' : 'esta',
'tah' : 'ta',
'tb':'tudo bem',
'tbm' : 'tambem',
'tbt':'retrocesso quinta feira',
'tc' : 'teclar',
'td' : 'tudo',
'tdb':'tudo bem',
'tds' : 'todos',
'te +' : 'ate mais',
'tks':'obrigado',
'u' : 'voce',
'uas':'risada',
'v6' : 'voces',
'vc':'voce',
'vcs':'voces',
'vdd':'verdade',
'vlw':'valeu',
'vs':'voce',
'wtf':'que porcaria e essa',
'xau' : 'tchau',
'xente' : 'gente',
'xoxo':'beijo',
'yolo':'so se vive uma vez',
'app' : 'aplicativo',
'pc': 'computador',
'ft': 'foto',
'tbm': 'também',
'net': 'internet',
'leg': 'travada',
'cel': 'celular',
'pr':'para',
'qnd':'quando',
'vo': 'vou',
'vms': 'vamos',
'etc': 'etecetera',
'oq': 'o que'
}
